export default function useSmartMovistarColumn() {
  return {
    Opciones: [
      { key: "status", label: "Estado SIM", width: 100 },
      // { key: "status", label: "Alias", width: 100 },
    ],
    SIMs: [
      { key: "alias_sim", label: "Alias", width: 100 },
      { key: "serial_number", label: "ICC SIM", width: 100 },
      { key: "msisdn", label: "N° MSISDN", width: 100 },
      // { key: "commercial_group", label: "Plan Comercial", width: 100 },
      { key: "commercial_group", label: "Grupo de suscripción", width: 100 },
    ],
    Estado_GPRS: [
      { key: "sim_model", label: "Modelo de SIM", width: 100 },
      { key: "status", label: "Estado", width: 100 },
      { key: "gpr_last_conn_start", label: "Inicio última conexión", width: 100 },
      { key: "gpr_last_conn_stop", label: "Termino última conexión", width: 100 },
    ],
    Consumo_Diario: [
      // { key: "consumption_monthly_data_limit", label: "MB contratados", width: 100 },
      { key: "consumption_monthly_voice_val", label: "Tráfico voz", width: 100 },
      { key: "consumption_monthly_sms_val", label: "Tráfico sms", width: 100 },
    ],
    Consumo_Mensual: [
      // { key: "consumption_monthly_data_limit", label: "MB contratados", width: 100 },
      { key: "consumption_monthly_voice_val", label: "Tráfico voz", width: 100 },
      { key: "consumption_monthly_sms_val", label: "Tráfico sms", width: 100 },
    ],
    Metadata: [
      { key: "imei", label: "IMEI", width: 100 },
      { key: "sim_apn", label: "APN", width: 100 },
      { key: "operator_sim", label: "Operador", width: 100 },
      { key: "country", label: "Pais", width: 100 },
      // { key: "country", label: "Última tecnología acceso detectada", width: 100 },
      // { key: "consumption_monthly_data_limit", label: "Tipo de plan", width: 100 },
      { key: "comm_module_manufacturer", label: "Fabricante Módulo comunicaciones", width: 100 },
      { key: "comm_module_model", label: "Modelo módulo comunicaciones", width: 100 },
      { key: "imei_last_change", label: "IMEI Último cambio", width: 100 },
      { key: "ip", label: "IP", width: 100 },
      { key: "static_ip", label: "IP Estática", width: 100 },
    ],
    Coordenadas_Locación_Automática: [
      { key: "latitude", label: "Latitud", width: 100 },
      { key: "longitude", label: "Longitud", width: 100 },
    ],
    Servicios_Básicos: [
      { key: "voiceoriginatedhome", label: "voiceOriginatedHome", width: 100 },
      { key: "voiceoriginatedroaming", label: "voiceOriginatedRoaming", width: 100 },
      { key: "voiceterminatedhome", label: "voiceTerminatedHome", width: 100 },
      { key: "voiceterminatedroaming", label: "voiceTerminatedRoaming", width: 100 },
      { key: "smsoriginatedhome", label: "smsOriginatedHome", width: 100 },
      { key: "smsoriginatedroaming", label: "smsOriginatedRoaming", width: 100 },
      { key: "smsterminatedhome", label: "smsTerminatedHome", width: 100 },
      { key: "smsterminatedroaming", label: "smsTerminatedRoaming", width: 100 },
    ],
    Fechas: [
      { key: "datahome", label: "dataHome", width: 100 },
      { key: "dataroaming", label: "dataRoaming", width: 100 },
      { key: "activation_date", label: "Activación de la SIM", width: 100 },
      { key: "last_con", label: "Última conexión", width: 100 },
    ],
    orderColumns: [
      { name: "Opciones", width: 100 },
      { name: "SIMs", width: 500 },
      { name: "Estado_GPRS", width: 500 },
      { name: "Consumo_Diario", width: 500 },
      { name: "Consumo_Mensual", width: 500 },
      { name: "Metadata", width: 500 },
      { name: "Coordenadas_Locación_Automática", width: 500 },
      { name: "Servicios_Básicos", width: 500 },
      { name: "Fechas", width: 500 },
    ],
  };
}
