import type { Metadata } from "next";
import { Inter, Open_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import SideBar from "@/components/SideBar/SideBar";
import ProviderRedux from "../components/ProviderRedux";

const open_sans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MCI Telecom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ProviderRedux>
      <html lang="en">
        <body className={open_sans.className}>
          <NavBar />
          <div className="flex">
            <SideBar />
            <div className="w-full">{children}</div>
          </div>
        </body>
      </html>
    </ProviderRedux>
  );
}
